# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Andrea Manera
title: Economist
email: andrea.manera04@gmail.com
#website: <a href="https://andmanera.github.io/amanera.github.io-master/">andmanera.github.io</a>

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  andmanera
# linkedin_username: andrea-manera
orcid_username: 0000-0003-2829-0065

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: > # Double new line is new line
  I am an Economist in the the Development Macroeconomics Research Division at
  the International Monetary Fund. I completed my PhD at the Massachusetts Institute
    of Technology in May 2022.

  My research focuses on the economics of innovation, technology adoption,
    automation, and related taxation and labor market policies. I
    employ a mix of theoretical, numerical and applied microeconomics empirical methods, relying on
    tools from Macroeconomics and Labor Economics.

  - Research interests: <mark>Economics of Automation</mark>,
    <mark>Economics of Innovation</mark>, <mark>Directed Technical Change</mark>,
    <mark>Economic Growth</mark>, <mark>Macroeconomics</mark>,
    <mark>Labor Economics</mark>, <mark>Macro-Finance</mark>.

  - Skills: <mark>MATLAB</mark> <mark>R</mark> <mark>Stata</mark>
      <mark>Python</mark> <mark>LaTeX</mark>


# Projects Section
#projects_title: Research

# Professional Activity
content:
  - layout: list
    title: Professional Activity
  #
  #
  # title: Professional Activity
  # description: |
  #   <b>Referee</b> for the Quarterly Journal of Economics, AER:Insights, Review of Economic Dynamics, International Journal of Manpower

# Experience Section
experience_title: Work Experience

# Education Section
educaton_title: Education

# Awards Section
# awards_title: Awards

# More Section
more_title: Miscellanea
more_content: >
  <b>Awards</b>
   - <i>Guido Cazzavillan PhD Fellowship</i>, Full tuition and stipend
   scholarship (2016).
   - <i>Bocconi Graduate Merit Award</i>. Full tuition scholarship
    awarded by Bocconi University (2012).

  <b>Languages</b>: Italian (Native),
   English (Proficient), French and Spanish (Good), some German and Bengali (Basic).

  <b>Personal Interests</b>
   Arthouse cinema, history books, classical, ancient and baroque music.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Dark mode
 # darkmode: false (options: true, false, never)

theme: jekyll-theme-minimal


exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
